### ISSUE TITLE
Minor discrepancy with fromHtmlEscapedString

### ISSUE THREAD

**Issue by lpsmith** [lpsmith/blaze-builder#1]
See jaspervdj/blaze-markup#15

`fromHtmlEscapedString` in [`0.4`](https://github.com/lpsmith/blaze-builder/blob/6bfbe383193859836c8832390c651ddef4e731ef/Blaze/ByteString/Builder/Html/Utf8.hs#L64) strips out '\DEL' as well as ASCII control characters,  whereas the same function from [`0.3`](https://github.com/lpsmith/blaze-builder/blob/2d8ce308951656ebf0318097989dc1c017dcff83/Blaze/ByteString/Builder/Html/Utf8.hs#L44) leaves them in.

e.g.  with blaze-builder-0.3.3.2

~~~
ghci> toLazyByteString (fromHtmlEscapedString "\DEL<foobar>\STX")
"\DEL&lt;foobar&gt;\STX"
~~~

with blaze-builder-0.4.0.0

~~~
ghci> toLazyByteString (fromHtmlEscapedString "\DEL<foobar>\STX")
"&lt;foobar&gt;"
~~~

Possible fixes would be to 1)  release a revision of the `0.3` series that also strips out control characters,  2) adjust `0.4` so that it doesn't,  or 3) leave it as-is.

It certainly is my intention that `0.4` be semantically identical to `0.3`,  but I am curious what the correct behavior should be here with regards to html escaping,  and how much trouble this discrepancy will actually cause.   Control characters aren't kosher in HTML,  but I don't know if they can actually lead to security vulnerabilities.    Similarly, this discrepancy does cause problems with `blaze-markup`'s test suite,  but I don't know if it'll cause any trouble in "real" applications.

**Comment by lpsmith** [comment]
Ok,  out of the [200 reverse dependencies of `blaze-builder` on hackage](http://packdeps.haskellers.com/reverse/blaze-builder),  there appears to be 3 direct reverse dependencies on `fromHtmlEscapedString`:

~~~
blaze-markup-0.6.3.0/src/Text/Blaze/Renderer/Utf8.hs
hackage-server-0.5.0/Distribution/Server/Framework/Templating.hs
lucid-2.9.1/src/Lucid/Base.hs
~~~

(This was done by scraping the package names out of the above link with grep and sed,   `cabal unpack` each one of the results,  then running `grep -rl fromHtmlEscapedString` on the directory of unpacked packages.)  

So if any maintainers of these packages would like to weigh in on this issue,  I'm all ears.   @dcoutts @jaspervdj @chrisdone

**Comment by lpsmith** [comment]
Of course,  this change also has the potential to affect the output of each one of these packages,  and thus any downstream dependencies of these packages as well.

**Comment by chrisdone** [comment]
I'm okay with this staying as-is. Given that it's an HTML5 parse error, even browsers would be legitimate in stripping it out, so relying on that for real applications is living on borrowed time anyway.

**Comment by jaspervdj** [comment]
I'm also fine with stripping out the control characters.
