### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by ndmitchell** [lpsmith/blaze-builder#12]
I am unable to test with newer GHC candidate releases because this package doesn't work with the Monoid/Semigroup proposal. I notice the code got merged, but there has been no subsequent release. Any chance you could fix that? Thanks!

**Comment by ndmitchell** [comment]
In fact, there are a few PR's open with such support, plus I see commits for it... Regardless, would be useful to have a released version with the support.

**Comment by sjakobi** [comment]
Bump! :)

**Comment by hvr** [comment]
It would be great if one of the PRs (e.g.  #14 or #13)  which make the `Semigroup` instance unconditionally defined could be merged before the next releases.

**Comment by phadej** [comment]
I (as [Hackage Trustee](https://github.com/haskell-infra/hackage-trustees)) [revised](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md) the bounds for 0.3.3.4, 0.4.0.0 0.4.0.1 and 0.4.0.2, e.g. http://hackage.haskell.org/package/blaze-builder-0.4.0.2/revisions/

**Comment by peti** [comment]
The lack of support for ghc 8.4.x currently breaks a *lot* of builds on that compiler. It would be really great to get a new release that fixes this issue.

**Comment by Evi1M4chine** [comment]
Ah, great, NOW I see this, AFTER I submitted a proper bug about it.

Guys, please use some proper titles! ^^

**Comment by ndmitchell** [comment]
If you look at HEAD you'd see the bug is fixed, so there is actually no work and no bug in HEAD - hence the title just to make a release :)

**Comment by hvr** [comment]
@ndmitchell well, actually there would be some work to be done, as the current state would result in an conditional API (c.f. https://github.com/lpsmith/blaze-builder/issues/12#issuecomment-371500329)

**Comment by sjakobi** [comment]
I'd like to point out that it's not hard to use `Data.Bytestring.Builder` directly instead of blaze-builder, if you can deal with a lower bound on `bytestring` of `>= 0.10.4`. See https://github.com/jaspervdj/websockets/pull/170.

BTW, `streaming-commons` also just [removed its dependency on `blaze-builder`](http://hackage.haskell.org/package/streaming-commons-0.2.0.0/changelog).

**Comment by RyanGlScott** [comment]
Moreover, if you _can't_ deal with that `bytestring` lower bound, you can also additionally depend on the [`bytestring-builder`](http://hackage.haskell.org/package/bytestring-builder) library, which backports the `Data.ByteString.Builder` interface to older GHCs.

**Comment by sjakobi** [comment]
> I'm considering extracting Blaze.ByteString.Builder.HTTP into a small new package

Published as [`bsb-http-chunked`](http://hackage.haskell.org/package/bsb-http-chunked).

> …so warp, http-streams and snap-server could remove their dependencies on blaze-builder.

I'll submit PRs for these.

**Comment by sjakobi** [comment]
@jaspervdj has released [v0.4.1.0](http://hackage.haskell.org/package/blaze-builder-0.4.1.0)
