### ISSUE TITLE
Support for bytestring 0.11

### ISSUE THREAD

**Issue by sjakobi** [lpsmith/blaze-builder#21]
http://hackage.haskell.org/package/bytestring-0.11.0.0/changelog

I suspect that bumping the bounds would be sufficient, but I haven't checked.

**Comment by sjakobi** [comment]
The `text` dependency needs a compatible release too though.

**Comment by andreasabel** [comment]
This issue seems to have been addressed by v0.4.2.0.

**Comment by sjakobi** [comment]
Thanks!
