### ISSUE TITLE
Actively maintained?

### ISSUE THREAD

**Issue by andreasabel** [lpsmith/blaze-builder#27]
Is this repo the place for active development of https://hackage.haskell.org/package/blaze-builder ?  (I think so, but I am not entirely sure.)

I am waiting for feedback on 
- [ ] #24 
- [ ] #25 
- [x] #26 

If help with maintenance is needed, I am hereby volunteering, for jobs such as CI and compatibility with new GHCs.

I think a version compatible with GHC 9.2 should be released in good time, so that `blaze-builder` is ready when GHC 9.2 is released.

**Comment by jaspervdj** [comment]
Hey @andreasabel, I'm happy to add you as a maintainer, but I don't have access to this.  Maybe @lpsmith can change this?

**Comment by andreasabel** [comment]
To me, it looks like @lpsmith has gone passive. 
If this is the case, the maintenance of `blaze-builder` should be moved to fork, ideally a new github community `blaze-builder`.
The current [hackage maintainers](https://hackage.haskell.org/package/blaze-builder/maintainers/) include you, @jaspervdj, so you should be able to add me there, at least.

**Comment by andreasabel** [comment]
I tried to contact @lpsmith via leon@melding-monads.com, but my email was not delivered:

On 2021-10-12 00:22, Andreas Abel wrote:
> Hello Leon,
> 
> trying to reach you via this email on your github profile...
> I hope all is well.
> 
> I contributed some PRs to lpsmith/blaze-builder, in particular, a CI and 
> a patch to build with GHC 9.2.  I would be happy to see my PRs merged 
> and a new version release, esp. since many packages depend on 
> blaze-builder and having a GHC 9.2-compatible version out in good time 
> would help the whole Haskell ecosystem to adapt to GHC 9.2.
> 
> If you would like some help with maintaining blaze-builder: I volunteer 
> to co-maintain.  In this case, please give me the necessary rights on 
> the repo and hackage.
> 
> All the best,
> Andreas

```
Delivery has failed to these recipients or groups:

leon@melding-monads.com
Your message couldn't be delivered. Despite repeated attempts to deliver your message, querying the Domain Name System (DNS) for the recipient's domain location information failed. 
```

**Comment by andreasabel** [comment]
> Hey @andreasabel, I'm happy to add you as a maintainer [...]

@jaspervdj : Would you add me to [hackage maintainers](https://hackage.haskell.org/package/blaze-builder/maintainers/)?  I can then sort out the rest.

**Comment by jaspervdj** [comment]
@andreasabel Done!  Let me know if you need anything else.

**Comment by andreasabel** [comment]
I researched for quite a while, but I could not find a push-button way to clone a github repo _together with its issues and its PRs_.  
It looks like when `blaze-builder` was moved from @meiersi to @lpsmith, the issues were not transfered either.
The owner can transfer issues, but I have no hope that @lpsmith will show up again.
So the new home will likely start with a fresh issue counter.

**Comment by andreasabel** [comment]
Candidate at: https://hackage.haskell.org/package/blaze-builder-0.4.2.2/candidate

**Comment by andreasabel** [comment]
New home at: https://github.com/blaze-builder/blaze-builder
