### ISSUE TITLE
Support HTML encoding of ByteString

### ISSUE THREAD

**Issue by dylex** [lpsmith/blaze-builder#7]
You often have ByteString data that is already properly (e.g., utf-8) encoded, that you want to include in HTML.  Currently, the only way to do this properly is to decode back to Text/String, and then encode to HTML.  However, it can be done directly and more efficiently by just doing HTML entity encoding on special characters and leaving the existing encoding (for 8-bit characters).  For example:
https://github.com/databrary/databrary/blob/master/Blaze/ByteString/Builder/Html/Word.hs

Does this seem reasonable? I'm happy to properly comment and clean this up and and submit a PR if so.

**Comment by dylex** [comment]
Also worth noting that using this approach for `fromHtmlEscapedText` results in a 2-3x speedup according to my benchmarks:
https://github.com/dylex/dwebework/blob/master/benchmark/blaze.hs
However this is mainly due to `Data.Text.Encoding.encodeUtf8Builder` being significantly faster than `Blaze.ByteString.Builder.Char.Utf8.fromText`.  A separate PR might consider switching the default implementation of all the `fromText` functions.

**Comment by winterland1989** [comment]
Yes, please make it happen, we should use `encodeUtf8Builder` instead of roll our own `fromText/fromLazyText`.

**Comment by lpsmith** [comment]
Yes, I will certainly entertain (and probably accept) a pull request.

**Comment by sjakobi** [comment]
This has been released in v0.4.1.0
